# Generated by Django 5.0.8 on 2024-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
