# Generated by Django 5.0.8 on 2024-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_logo',
            field=models.BooleanField(default=True),
        ),
    ]
