# Generated by Django 5.0.8 on 2024-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_media_is_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_logo',
            field=models.BooleanField(default=False),
        ),
    ]
